cicd(Create pipeline #4): Try another reporter 2

diff --git a/.github/workflows/pre-build-checks.yaml b/.github/workflows/pre-build-checks.yaml
--- a/.github/workflows/pre-build-checks.yaml
+++ b/.github/workflows/pre-build-checks.yaml
@@ -55,11 +55,18 @@ jobs:
         run: poetry install --no-interaction --no-ansi
       - name: Pytest
         run: poetry run pytest -v
-      - name: Surface failing tests
-        if: always()
-        uses: pmeier/pytest-results-action@main
+      # - name: Surface failing tests
+      #   if: always()
+      #   uses: pmeier/pytest-results-action@main
+      #   with:
+      #     path: junit.xml
+      #     summary: true
+      #     fail-on-empty: true
+      #     title: Test results
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          path: junit.xml
-          summary: true
-          fail-on-empty: true
-          title: Test results
+          name: JUNIT Tests            # Name of the check run which will be created
+          path: junit.xml    # Path to test results
+          reporter: java-junit        # Format of test results
